package com.kidsgame.mathapp.quiz;

public enum QuizMode {
    ADDITION,
    SUBTRACTION,
    MIXED,
    UNKNOWN_ADDITION,
    UNKNOWN_SUBTRACTION,
    UNKNOWN_MIXED,
    MULTIPLICATION,
    DIVISION,
    MULTIPLICATION_DIVISION,
    COMPARE,
    WORD_LETTERS,
    WORD_SYLLABLES,
    WORD_TYPING,
    WORD_PICTURE,
    WORD_MISSING_LETTER,
    WORD_FIRST_LETTER_GROUP,
    WORD_WRONG_LETTER,
    FIND_OBJECT,
    SPOT_DIFFERENCES,
    MEMORY_PAIRS,
    PATTERN_SEQUENCE,
    CUSTOM_GROUP,
    ALL_GROUP
}
