package com.kidsgame.mathapp.quiz;

import java.util.List;

public final class SuggestedBulgarianImageCatalog {
    private SuggestedBulgarianImageCatalog() {
    }

    public static List<SuggestedWord> words() {
        return WORDS;
    }

    public record SuggestedWord(String word, String image) {
    }

    private static final List<SuggestedWord> WORDS = List.of(
            new SuggestedWord("дете", "🧒"),
            new SuggestedWord("момче", "👦"),
            new SuggestedWord("човек", "🧑"),
            new SuggestedWord("фермер", "🧑‍🌾"),
            new SuggestedWord("художник", "🧑‍🎨"),
            new SuggestedWord("майстор", "🧑‍🔧"),
            new SuggestedWord("космонавт", "🧑‍🚀"),
            new SuggestedWord("учен", "🧑‍🔬"),
            new SuggestedWord("програмист", "🧑‍💻"),
            new SuggestedWord("семейство", "👨‍👩‍👧"),
            new SuggestedWord("длани", "🤲"),
            new SuggestedWord("пляскане", "👏"),
            new SuggestedWord("палец нагоре", "👍"),
            new SuggestedWord("махане", "👋"),
            new SuggestedWord("хамстер", "🐹"),
            new SuggestedWord("коала", "🐨"),
            new SuggestedWord("теленце", "🐮"),
            new SuggestedWord("маймунка", "🐵"),
            new SuggestedWord("птица", "🐦"),
            new SuggestedWord("патица", "🦆"),
            new SuggestedWord("орел", "🦅"),
            new SuggestedWord("бухал", "🦉"),
            new SuggestedWord("прилеп", "🦇"),
            new SuggestedWord("вълк", "🐺"),
            new SuggestedWord("глиган", "🐗"),
            new SuggestedWord("кон", "🐴"),
            new SuggestedWord("еднорог", "🦄"),
            new SuggestedWord("червей", "🪱"),
            new SuggestedWord("гъсеница", "🐛"),
            new SuggestedWord("муха", "🪰"),
            new SuggestedWord("бръмбар", "🪲"),
            new SuggestedWord("паяк", "🕷️"),
            new SuggestedWord("скорпион", "🦂"),
            new SuggestedWord("змия", "🐍"),
            new SuggestedWord("гущер", "🦎"),
            new SuggestedWord("калмар", "🦑"),
            new SuggestedWord("скарида", "🦐"),
            new SuggestedWord("омар", "🦞"),
            new SuggestedWord("шарена рибка", "🐠"),
            new SuggestedWord("риба балон", "🐡"),
            new SuggestedWord("делфин", "🐬"),
            new SuggestedWord("кит", "🐳"),
            new SuggestedWord("акула", "🦈"),
            new SuggestedWord("бенгалски тигър", "🐅"),
            new SuggestedWord("леопард", "🐆"),
            new SuggestedWord("горила", "🦍"),
            new SuggestedWord("орангутан", "🦧"),
            new SuggestedWord("мамут", "🦣"),
            new SuggestedWord("хипопотам", "🦛"),
            new SuggestedWord("носорог", "🦏"),
            new SuggestedWord("камила с една гърбица", "🐪"),
            new SuggestedWord("кенгуру", "🦘"),
            new SuggestedWord("бизон", "🦬"),
            new SuggestedWord("бивол", "🐃"),
            new SuggestedWord("бик", "🐂"),
            new SuggestedWord("бягащ кон", "🐎"),
            new SuggestedWord("прасенце", "🐖"),
            new SuggestedWord("овен", "🐏"),
            new SuggestedWord("лама", "🦙"),
            new SuggestedWord("елен", "🦌"),
            new SuggestedWord("домашно куче", "🐕"),
            new SuggestedWord("домашна котка", "🐈"),
            new SuggestedWord("перо", "🪶"),
            new SuggestedWord("папагал", "🦜"),
            new SuggestedWord("лебед", "🦢"),
            new SuggestedWord("фламинго", "🦩"),
            new SuggestedWord("паун", "🦚"),
            new SuggestedWord("видра", "🦦"),
            new SuggestedWord("бобър", "🦫"),
            new SuggestedWord("таралеж", "🦔"),
            new SuggestedWord("зелена ябълка", "🍏"),
            new SuggestedWord("боровинки", "🫐"),
            new SuggestedWord("пъпеш", "🍈"),
            new SuggestedWord("манго", "🥭"),
            new SuggestedWord("ананас", "🍍"),
            new SuggestedWord("кокос", "🥥"),
            new SuggestedWord("киви", "🥝"),
            new SuggestedWord("авокадо", "🥑"),
            new SuggestedWord("броколи", "🥦"),
            new SuggestedWord("зелена салата", "🥬"),
            new SuggestedWord("краставица", "🥒"),
            new SuggestedWord("люта чушка", "🌶️"),
            new SuggestedWord("чушка", "🫑"),
            new SuggestedWord("маслина", "🫒"),
            new SuggestedWord("чесън", "🧄"),
            new SuggestedWord("сладък картоф", "🍠"),
            new SuggestedWord("кроасан", "🥐"),
            new SuggestedWord("франзела", "🥖"),
            new SuggestedWord("геврек", "🥨"),
            new SuggestedWord("сирене", "🧀"),
            new SuggestedWord("палачинки", "🥞"),
            new SuggestedWord("вафла", "🧇"),
            new SuggestedWord("кравайче", "🥯"),
            new SuggestedWord("купичка", "🥣"),
            new SuggestedWord("салата", "🥗"),
            new SuggestedWord("нудли", "🍜"),
            new SuggestedWord("спагети", "🍝"),
            new SuggestedWord("ориз", "🍚"),
            new SuggestedWord("оризова топка", "🍙"),
            new SuggestedWord("оризов крекер", "🍘"),
            new SuggestedWord("рибно рулце", "🍥"),
            new SuggestedWord("кнедли", "🥟"),
            new SuggestedWord("късметче", "🥠"),
            new SuggestedWord("лунен сладкиш", "🥮"),
            new SuggestedWord("шишче", "🍢"),
            new SuggestedWord("десертно шишче", "🍡"),
            new SuggestedWord("леден десерт", "🍧"),
            new SuggestedWord("сладолед в купичка", "🍨"),
            new SuggestedWord("пай", "🥧"),
            new SuggestedWord("кексче", "🧁"),
            new SuggestedWord("парче торта", "🍰"),
            new SuggestedWord("крем карамел", "🍮"),
            new SuggestedWord("близалка", "🍭"),
            new SuggestedWord("шоколад", "🍫"),
            new SuggestedWord("пуканки", "🍿"),
            new SuggestedWord("поничка", "🍩"),
            new SuggestedWord("бисквита", "🍪"),
            new SuggestedWord("кестен", "🌰"),
            new SuggestedWord("фъстъци", "🥜"),
            new SuggestedWord("мляко", "🥛"),
            new SuggestedWord("чай с мляко", "🧋"),
            new SuggestedWord("кълн", "🌱"),
            new SuggestedWord("билка", "🌿"),
            new SuggestedWord("детелина", "☘️"),
            new SuggestedWord("четирилистна детелина", "🍀"),
            new SuggestedWord("бамбук", "🎋"),
            new SuggestedWord("сухо листо", "🍂"),
            new SuggestedWord("есенно листо", "🍁"),
            new SuggestedWord("саксия", "🪴"),
            new SuggestedWord("кактус", "🌵"),
            new SuggestedWord("бор", "🌲"),
            new SuggestedWord("палма", "🌴"),
            new SuggestedWord("жито", "🌾"),
            new SuggestedWord("хибискус", "🌺"),
            new SuggestedWord("роза", "🌹"),
            new SuggestedWord("увяхнала роза", "🥀"),
            new SuggestedWord("лале", "🌷"),
            new SuggestedWord("цвят", "🌸"),
            new SuggestedWord("букет", "💐"),
            new SuggestedWord("земя", "🌎"),
            new SuggestedWord("искри", "✨"),
            new SuggestedWord("слънце с облак", "🌤️"),
            new SuggestedWord("облачно слънце", "⛅"),
            new SuggestedWord("дъждовно слънце", "🌦️"),
            new SuggestedWord("буря", "⛈️"),
            new SuggestedWord("гръмотевица", "🌩️"),
            new SuggestedWord("сняг с облак", "🌨️"),
            new SuggestedWord("снежен човек", "☃️"),
            new SuggestedWord("вятър", "🌬️"),
            new SuggestedWord("въздушна струя", "💨"),
            new SuggestedWord("дъждовен чадър", "☔"),
            new SuggestedWord("капка", "💧"),
            new SuggestedWord("снежна планина", "🏔️"),
            new SuggestedWord("къмпинг", "🏕️"),
            new SuggestedWord("къщи", "🏘️"),
            new SuggestedWord("тоалетна", "🚽"),
            new SuggestedWord("душ", "🚿"),
            new SuggestedWord("вана", "🛁"),
            new SuggestedWord("сапун", "🧼"),
            new SuggestedWord("гъба за чистене", "🧽"),
            new SuggestedWord("метла", "🧹"),
            new SuggestedWord("кош за пране", "🧺"),
            new SuggestedWord("кофа", "🪣"),
            new SuggestedWord("огледало", "🪞"),
            new SuggestedWord("четка за зъби", "🪥"),
            new SuggestedWord("лосион", "🧴"),
            new SuggestedWord("хартия", "🧻"),
            new SuggestedWord("матрьошка", "🪆"),
            new SuggestedWord("йойо", "🪀"),
            new SuggestedWord("хвърчило", "🪁"),
            new SuggestedWord("пързалка", "🛝"),
            new SuggestedWord("пинята", "🪅"),
            new SuggestedWord("панделка", "🎀"),
            new SuggestedWord("свещ", "🕯️"),
            new SuggestedWord("стар часовник", "🕰️"),
            new SuggestedWord("тухла", "🧱"),
            new SuggestedWord("куфар с инструменти", "🧰"),
            new SuggestedWord("стълба", "🪜"),
            new SuggestedWord("куфар", "🧳"),
            new SuggestedWord("зелена книга", "📗"),
            new SuggestedWord("червена книга", "📕"),
            new SuggestedWord("оранжева книга", "📙"),
            new SuggestedWord("много книги", "📚"),
            new SuggestedWord("отворена книга", "📖"),
            new SuggestedWord("бележка", "📝"),
            new SuggestedWord("пастел", "🖍️"),
            new SuggestedWord("писалка", "🖊️"),
            new SuggestedWord("писалка с мастило", "🖋️"),
            new SuggestedWord("перодръжка", "✒️"),
            new SuggestedWord("триъгълник за чертане", "📐"),
            new SuggestedWord("линия", "📏"),
            new SuggestedWord("сметало", "🧮"),
            new SuggestedWord("кламер", "📎"),
            new SuggestedWord("два кламера", "🖇️"),
            new SuggestedWord("кабарче", "📌"),
            new SuggestedWord("пинче", "📍"),
            new SuggestedWord("папки", "🗂️"),
            new SuggestedWord("папка", "📁"),
            new SuggestedWord("отворена папка", "📂"),
            new SuggestedWord("лист за бележки", "🗒️"),
            new SuggestedWord("малка тетрадка", "📔"),
            new SuggestedWord("синя тетрадка", "📓"),
            new SuggestedWord("бележник", "📒"),
            new SuggestedWord("календар с лист", "🗓️"),
            new SuggestedWord("календар", "📅"),
            new SuggestedWord("лупа", "🔍"),
            new SuggestedWord("малка лупа", "🔎"),
            new SuggestedWord("епруветка", "🧪"),
            new SuggestedWord("микроскоп", "🔬"),
            new SuggestedWord("термометър", "🌡️"),
            new SuggestedWord("ген", "🧬"),
            new SuggestedWord("клавиатура", "⌨️"),
            new SuggestedWord("мишка за компютър", "🖱️"),
            new SuggestedWord("принтер", "🖨️"),
            new SuggestedWord("мобилен телефон", "📱"),
            new SuggestedWord("фотоапарат", "📷"),
            new SuggestedWord("слушалки", "🎧"),
            new SuggestedWord("такси", "🚕"),
            new SuggestedWord("тролей", "🚎"),
            new SuggestedWord("спортна кола", "🏎️"),
            new SuggestedWord("полицейска кола", "🚓"),
            new SuggestedWord("линейка", "🚑"),
            new SuggestedWord("пожарна кола", "🚒"),
            new SuggestedWord("микробус", "🚐"),
            new SuggestedWord("пикап", "🛻"),
            new SuggestedWord("камион", "🚚"),
            new SuggestedWord("голям камион", "🚛"),
            new SuggestedWord("скутер", "🛵"),
            new SuggestedWord("велосипед", "🚲"),
            new SuggestedWord("тротинетка", "🛴"),
            new SuggestedWord("ролкови кънки", "🛼"),
            new SuggestedWord("влакче", "🚆"),
            new SuggestedWord("метро", "🚇"),
            new SuggestedWord("трамвай", "🚊"),
            new SuggestedWord("спирка", "🚉"),
            new SuggestedWord("излитащ самолет", "🛫"),
            new SuggestedWord("кацащ самолет", "🛬"),
            new SuggestedWord("летяща чиния", "🛸"),
            new SuggestedWord("моторна лодка", "🚤"),
            new SuggestedWord("яхта", "🛥️"),
            new SuggestedWord("котва", "⚓"),
            new SuggestedWord("спасителен пояс", "🛟"),
            new SuggestedWord("хоризонтален светофар", "🚥"),
            new SuggestedWord("знак стоп", "🛑"),
            new SuggestedWord("бензин", "⛽"),
            new SuggestedWord("гума", "🛞"),
            new SuggestedWord("американски футбол", "🏈"),
            new SuggestedWord("бейзбол", "⚾"),
            new SuggestedWord("софтбол", "🥎"),
            new SuggestedWord("тенис", "🎾"),
            new SuggestedWord("волейбол", "🏐"),
            new SuggestedWord("ръгби", "🏉"),
            new SuggestedWord("фризби", "🥏"),
            new SuggestedWord("билярд", "🎱"),
            new SuggestedWord("тенис на маса", "🏓"),
            new SuggestedWord("бадминтон", "🏸"),
            new SuggestedWord("хокей", "🏒"),
            new SuggestedWord("хокей на трева", "🏑"),
            new SuggestedWord("лакрос", "🥍"),
            new SuggestedWord("крикет", "🏏"),
            new SuggestedWord("бумеранг", "🪃"),
            new SuggestedWord("голф", "⛳"),
            new SuggestedWord("въдица", "🎣"),
            new SuggestedWord("маска за гмуркане", "🤿"),
            new SuggestedWord("спортна фланелка", "🎽"),
            new SuggestedWord("скейтборд", "🛹"),
            new SuggestedWord("шейна", "🛷"),
            new SuggestedWord("кънки", "⛸️"),
            new SuggestedWord("кърлинг", "🥌"),
            new SuggestedWord("ски", "🎿"),
            new SuggestedWord("скиор", "⛷️"),
            new SuggestedWord("сноуборд", "🏂"),
            new SuggestedWord("щанги", "🏋️"),
            new SuggestedWord("гимнастика", "🤸"),
            new SuggestedWord("хандбал", "🤾"),
            new SuggestedWord("голф играч", "🏌️"),
            new SuggestedWord("жокей", "🏇"),
            new SuggestedWord("йога", "🧘"),
            new SuggestedWord("плуване", "🏊"),
            new SuggestedWord("колоездене", "🚴"),
            new SuggestedWord("златен медал", "🥇"),
            new SuggestedWord("сребърен медал", "🥈"),
            new SuggestedWord("бронзов медал", "🥉"),
            new SuggestedWord("ноти", "🎶"),
            new SuggestedWord("партитура", "🎼"),
            new SuggestedWord("тамтам", "🪘"),
            new SuggestedWord("саксофон", "🎷"),
            new SuggestedWord("тромпет", "🎺"),
            new SuggestedWord("акордеон", "🪗"),
            new SuggestedWord("банджо", "🪕"),
            new SuggestedWord("радио", "📻"),
            new SuggestedWord("кино прожектор", "📽️"),
            new SuggestedWord("филмова лента", "🎞️"),
            new SuggestedWord("камера със светкавица", "📸"),
            new SuggestedWord("пощенски рог", "📯"),
            new SuggestedWord("празник", "🥳"),
            new SuggestedWord("конфети", "🎉"),
            new SuggestedWord("серпентини", "🎊"),
            new SuggestedWord("диамант", "💎"),
            new SuggestedWord("магическа пръчка", "🪄"),
            new SuggestedWord("оранжево сърце", "🧡"),
            new SuggestedWord("жълто сърце", "💛"),
            new SuggestedWord("зелено сърце", "💚"),
            new SuggestedWord("синьо сърце", "💙"),
            new SuggestedWord("лилаво сърце", "💜"),
            new SuggestedWord("бяло сърце", "🤍"),
            new SuggestedWord("кафяво сърце", "🤎"),
            new SuggestedWord("червен кръг", "🔴"),
            new SuggestedWord("оранжев кръг", "🟠"),
            new SuggestedWord("жълт кръг", "🟡"),
            new SuggestedWord("зелен кръг", "🟢"),
            new SuggestedWord("син кръг", "🔵"),
            new SuggestedWord("лилав кръг", "🟣"),
            new SuggestedWord("кафяв кръг", "🟤"),
            new SuggestedWord("бял кръг", "⚪"),
            new SuggestedWord("черен кръг", "⚫"),
            new SuggestedWord("червен квадрат", "🟥"),
            new SuggestedWord("оранжев квадрат", "🟧"),
            new SuggestedWord("жълт квадрат", "🟨"),
            new SuggestedWord("зелен квадрат", "🟩"),
            new SuggestedWord("син квадрат", "🟦"),
            new SuggestedWord("лилав квадрат", "🟪"),
            new SuggestedWord("бял квадрат", "⬜"),
            new SuggestedWord("черен квадрат", "⬛"),
            new SuggestedWord("голям оранжев ромб", "🔶"),
            new SuggestedWord("голям син ромб", "🔷"),
            new SuggestedWord("малък оранжев ромб", "🔸"),
            new SuggestedWord("малък син ромб", "🔹"),
            new SuggestedWord("червен триъгълник", "🔺"),
            new SuggestedWord("обърнат триъгълник", "🔻"),
            new SuggestedWord("син диамант", "💠"),
            new SuggestedWord("спирала", "🌀"),
            new SuggestedWord("плюс", "➕"),
            new SuggestedWord("минус", "➖"),
            new SuggestedWord("знак умножение", "✖️"),
            new SuggestedWord("знак деление", "➗"),
            new SuggestedWord("отметка", "✅")
    );
}
