services:
  postgres:
    image: postgres:18-alpine
    container_name: kids-game-postgres
    environment:
      POSTGRES_DB: kids_game
      POSTGRES_USER: kids
      POSTGRES_PASSWORD: kids
    ports:
      - "5432:5432"
    volumes:
      - kids-game-postgres-18-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kids -d kids_game"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  kids-game-postgres-18-data:
