insert into reward_catalog_items (
    id,
    theme_id,
    theme_ids,
    category,
    name,
    price,
    image,
    default_scale,
    min_scale,
    max_scale,
    active,
    created_at,
    updated_at
) values
    ('space-star', 'space', 'space', 'Космос', 'Звезда', 10, '/reward-assets/space/star.svg', 0.70, 0.35, 1.60, true, now(), now()),
    ('space-sun', 'space', 'space', 'Космос', 'Слънце', 80, '/reward-assets/space/sun.svg', 1.15, 0.55, 2.40, true, now(), now()),
    ('space-planet', 'space', 'space', 'Планети', 'Планета', 40, '/reward-assets/space/planet.svg', 1.00, 0.50, 2.20, true, now(), now()),
    ('space-mercury', 'space', 'space', 'Планети', 'Меркурий', 25, '/reward-assets/space/mercury.svg', 0.75, 0.35, 1.60, true, now(), now()),
    ('space-venus', 'space', 'space', 'Планети', 'Венера', 30, '/reward-assets/space/venus.svg', 0.85, 0.40, 1.80, true, now(), now()),
    ('space-earth', 'space', 'space', 'Планети', 'Земя', 40, '/reward-assets/space/earth.svg', 0.90, 0.45, 1.90, true, now(), now()),
    ('space-mars', 'space', 'space', 'Планети', 'Марс', 35, '/reward-assets/space/mars.svg', 0.85, 0.40, 1.80, true, now(), now()),
    ('space-jupiter', 'space', 'space', 'Планети', 'Юпитер', 65, '/reward-assets/space/jupiter.svg', 1.15, 0.55, 2.50, true, now(), now()),
    ('space-saturn', 'space', 'space', 'Планети', 'Сатурн', 65, '/reward-assets/space/saturn.svg', 1.20, 0.55, 2.60, true, now(), now()),
    ('space-uranus', 'space', 'space', 'Планети', 'Уран', 50, '/reward-assets/space/uranus.svg', 1.00, 0.50, 2.20, true, now(), now()),
    ('space-neptune', 'space', 'space', 'Планети', 'Нептун', 50, '/reward-assets/space/neptune.svg', 1.00, 0.50, 2.20, true, now(), now()),
    ('space-moon', 'space', 'space', 'Космос', 'Луна', 25, '/reward-assets/space/moon.svg', 0.75, 0.35, 1.60, true, now(), now()),
    ('space-comet', 'space', 'space', 'Космос', 'Комета', 45, '/reward-assets/space/comet.svg', 1.00, 0.45, 2.10, true, now(), now()),
    ('space-asteroid', 'space', 'space', 'Космос', 'Астероид', 20, '/reward-assets/space/asteroid.svg', 0.75, 0.35, 1.60, true, now(), now()),
    ('space-rocket', 'space', 'space', 'Кораби', 'Ракета', 100, '/reward-assets/space/rocket.svg', 1.00, 0.50, 2.20, true, now(), now()),
    ('space-astronaut', 'space', 'space', 'Герои', 'Космонавт', 120, '/reward-assets/space/astronaut.svg', 1.00, 0.50, 2.20, true, now(), now()),
    ('space-robot', 'space', 'space', 'Герои', 'Робот', 80, '/reward-assets/space/robot.svg', 0.95, 0.50, 2.00, true, now(), now()),
    ('space-satellite', 'space', 'space', 'Кораби', 'Сателит', 90, '/reward-assets/space/satellite.svg', 0.95, 0.45, 2.00, true, now(), now()),
    ('space-station', 'space', 'space', 'Станции', 'Космическа станция', 130, '/reward-assets/space/space-station.svg', 1.25, 0.60, 2.70, true, now(), now()),
    ('space-milky-way', 'space', 'space', 'Галактики', 'Млечен път', 100, '/reward-assets/space/milky-way.svg', 1.35, 0.65, 2.80, true, now(), now()),
    ('space-ufo', 'space', 'space', 'Кораби', 'НЛО кораб', 90, '/reward-assets/space/ufo.svg', 1.05, 0.50, 2.20, true, now(), now()),
    ('space-black-hole', 'space', 'space', 'Галактики', 'Черна дупка', 110, '/reward-assets/space/black-hole.svg', 1.15, 0.55, 2.40, true, now(), now()),
    ('space-nebula', 'space', 'space', 'Галактики', 'Мъглявина', 80, '/reward-assets/space/nebula.svg', 1.20, 0.55, 2.50, true, now(), now()),
    ('space-rover', 'space', 'space', 'Кораби', 'Марсоход', 95, '/reward-assets/space/rover.svg', 1.00, 0.50, 2.10, true, now(), now()),
    ('space-telescope', 'space', 'space', 'Кораби', 'Космически телескоп', 100, '/reward-assets/space/telescope.svg', 1.00, 0.50, 2.20, true, now(), now()),
    ('space-alien', 'space', 'space', 'Герои', 'Извънземно', 75, '/reward-assets/space/alien.svg', 0.90, 0.45, 1.90, true, now(), now()),
    ('space-constellation', 'space', 'space', 'Галактики', 'Съзвездие', 55, '/reward-assets/space/constellation.svg', 1.00, 0.50, 2.20, true, now(), now())
on conflict (id) do update
set theme_id = excluded.theme_id,
    theme_ids = excluded.theme_ids,
    category = excluded.category,
    name = excluded.name,
    price = excluded.price,
    image = excluded.image,
    default_scale = excluded.default_scale,
    min_scale = excluded.min_scale,
    max_scale = excluded.max_scale,
    active = true,
    updated_at = now();
