insert into reward_catalog_items (
    id,
    theme_id,
    theme_ids,
    category,
    name,
    price,
    image,
    default_scale,
    min_scale,
    max_scale,
    active,
    created_at,
    updated_at
) values
    ('sea-fish', 'underwater', 'underwater', 'Риби', 'Синя рибка', 30, '/reward-assets/sea/fish-blue.svg', 0.85, 0.40, 1.80, true, now(), now()),
    ('sea-yellow-fish', 'underwater', 'underwater', 'Риби', 'Жълта рибка', 30, '/reward-assets/sea/fish-yellow.svg', 0.85, 0.40, 1.80, true, now(), now()),
    ('sea-red-fish', 'underwater', 'underwater', 'Риби', 'Червена рибка', 30, '/reward-assets/sea/fish-red.svg', 0.85, 0.40, 1.80, true, now(), now()),
    ('sea-purple-fish', 'underwater', 'underwater', 'Риби', 'Лилава рибка', 30, '/reward-assets/sea/fish-purple.svg', 0.85, 0.40, 1.80, true, now(), now()),
    ('sea-goldfish', 'underwater', 'underwater', 'Риби', 'Златна рибка', 40, '/reward-assets/sea/goldfish.svg', 0.85, 0.40, 1.80, true, now(), now()),
    ('sea-clownfish', 'underwater', 'underwater', 'Риби', 'Рибка клоун', 45, '/reward-assets/sea/clownfish.svg', 0.90, 0.42, 1.90, true, now(), now()),
    ('sea-dolphin', 'underwater', 'underwater', 'Морски животни', 'Делфин', 100, '/reward-assets/sea/dolphin.svg', 1.15, 0.55, 2.45, true, now(), now()),
    ('sea-whale', 'underwater', 'underwater', 'Морски животни', 'Кит', 120, '/reward-assets/sea/whale.svg', 1.25, 0.60, 2.70, true, now(), now()),
    ('sea-shark', 'underwater', 'underwater', 'Морски животни', 'Акула', 110, '/reward-assets/sea/shark.svg', 1.20, 0.60, 2.55, true, now(), now()),
    ('sea-turtle', 'underwater', 'underwater', 'Морски животни', 'Костенурка', 80, '/reward-assets/sea/turtle.svg', 0.95, 0.45, 2.00, true, now(), now()),
    ('sea-stingray', 'underwater', 'underwater', 'Морски животни', 'Скат', 85, '/reward-assets/sea/stingray.svg', 1.05, 0.50, 2.25, true, now(), now()),
    ('sea-octopus', 'underwater', 'underwater', 'Морски животни', 'Октопод', 85, '/reward-assets/sea/octopus.svg', 0.95, 0.45, 2.00, true, now(), now()),
    ('sea-jellyfish', 'underwater', 'underwater', 'Морски животни', 'Медуза', 60, '/reward-assets/sea/jellyfish.svg', 0.95, 0.45, 2.00, true, now(), now()),
    ('sea-seahorse-yellow', 'underwater', 'underwater', 'Морски животни', 'Жълто морско конче', 55, '/reward-assets/sea/seahorse-yellow.svg', 0.90, 0.42, 1.95, true, now(), now()),
    ('sea-seahorse-purple', 'underwater', 'underwater', 'Морски животни', 'Лилаво морско конче', 55, '/reward-assets/sea/seahorse-purple.svg', 0.90, 0.42, 1.95, true, now(), now()),
    ('sea-crab', 'underwater', 'underwater', 'Морски животни', 'Червен рак', 40, '/reward-assets/sea/crab-red.svg', 0.85, 0.40, 1.85, true, now(), now()),
    ('sea-blue-crab', 'underwater', 'underwater', 'Морски животни', 'Син рак', 40, '/reward-assets/sea/crab-blue.svg', 0.85, 0.40, 1.85, true, now(), now()),
    ('sea-star', 'underwater', 'underwater', 'Морско дъно', 'Оранжева морска звезда', 20, '/reward-assets/sea/starfish-orange.svg', 0.70, 0.35, 1.60, true, now(), now()),
    ('sea-pink-starfish', 'underwater', 'underwater', 'Морско дъно', 'Розова морска звезда', 20, '/reward-assets/sea/starfish-pink.svg', 0.70, 0.35, 1.60, true, now(), now()),
    ('sea-seaweed', 'underwater', 'underwater', 'Растения', 'Високи водорасли', 15, '/reward-assets/sea/seaweed-tall.svg', 0.95, 0.45, 2.05, true, now(), now()),
    ('sea-curly-seaweed', 'underwater', 'underwater', 'Растения', 'Къдрави водорасли', 15, '/reward-assets/sea/seaweed-curly.svg', 0.95, 0.45, 2.05, true, now(), now()),
    ('sea-coral', 'underwater', 'underwater', 'Корали', 'Червен корал', 30, '/reward-assets/sea/coral-red.svg', 0.95, 0.45, 2.05, true, now(), now()),
    ('sea-purple-coral', 'underwater', 'underwater', 'Корали', 'Лилав корал', 30, '/reward-assets/sea/coral-purple.svg', 0.95, 0.45, 2.05, true, now(), now()),
    ('sea-fan-coral', 'underwater', 'underwater', 'Корали', 'Ветрило корал', 35, '/reward-assets/sea/coral-fan.svg', 1.00, 0.45, 2.10, true, now(), now()),
    ('sea-shell', 'underwater', 'underwater', 'Морско дъно', 'Мида', 20, '/reward-assets/sea/shell.svg', 0.70, 0.35, 1.50, true, now(), now()),
    ('sea-rapan', 'underwater', 'underwater', 'Морско дъно', 'Рапан', 20, '/reward-assets/sea/rapan.svg', 0.75, 0.35, 1.60, true, now(), now()),
    ('sea-pearl-shell', 'underwater', 'underwater', 'Морско дъно', 'Мида с перла', 35, '/reward-assets/sea/pearl-shell.svg', 0.75, 0.35, 1.60, true, now(), now()),
    ('sea-treasure', 'underwater', 'underwater', 'Съкровища', 'Съкровище', 120, '/reward-assets/sea/treasure-chest.svg', 1.00, 0.50, 2.20, true, now(), now()),
    ('sea-anchor', 'underwater', 'underwater', 'Съкровища', 'Котва', 45, '/reward-assets/sea/anchor.svg', 0.95, 0.45, 2.00, true, now(), now()),
    ('sea-bubbles', 'underwater', 'underwater', 'Украси', 'Мехурчета', 10, '/reward-assets/sea/bubbles.svg', 0.90, 0.40, 1.90, true, now(), now()),
    ('sea-submarine', 'underwater', 'underwater', 'Предмети', 'Подводница', 100, '/reward-assets/sea/submarine.svg', 1.15, 0.55, 2.45, true, now(), now())
on conflict (id) do update
set theme_id = excluded.theme_id,
    theme_ids = excluded.theme_ids,
    category = excluded.category,
    name = excluded.name,
    price = excluded.price,
    image = excluded.image,
    default_scale = excluded.default_scale,
    min_scale = excluded.min_scale,
    max_scale = excluded.max_scale,
    active = true,
    updated_at = now();
