insert into reward_catalog_items (
    id,
    theme_id,
    theme_ids,
    category,
    name,
    price,
    image,
    default_scale,
    min_scale,
    max_scale,
    active,
    created_at,
    updated_at
) values
    ('farm-sheep-ewe', 'farm', 'farm', 'Животни', 'Овца', 55, '/reward-assets/farm/sheep-ewe.svg', 0.95, 0.45, 2.05, true, now(), now()),
    ('farm-sheep-ram', 'farm', 'farm', 'Животни', 'Овен', 60, '/reward-assets/farm/sheep-ram.svg', 1.00, 0.45, 2.15, true, now(), now()),
    ('farm-lamb', 'farm', 'farm', 'Животни', 'Агънце', 40, '/reward-assets/farm/lamb.svg', 0.75, 0.35, 1.60, true, now(), now()),
    ('farm-goat-doe', 'farm', 'farm', 'Животни', 'Коза', 55, '/reward-assets/farm/goat-doe.svg', 0.95, 0.45, 2.05, true, now(), now()),
    ('farm-goat-buck', 'farm', 'farm', 'Животни', 'Козел', 60, '/reward-assets/farm/goat-buck.svg', 1.00, 0.45, 2.15, true, now(), now()),
    ('farm-kid-goat', 'farm', 'farm', 'Животни', 'Яре', 40, '/reward-assets/farm/kid-goat.svg', 0.75, 0.35, 1.60, true, now(), now()),
    ('farm-hen-white', 'farm', 'farm', 'Животни', 'Бяла кокошка', 35, '/reward-assets/farm/hen-white.svg', 0.78, 0.35, 1.65, true, now(), now()),
    ('farm-hen-brown', 'farm', 'farm', 'Животни', 'Кафява кокошка', 35, '/reward-assets/farm/hen-brown.svg', 0.78, 0.35, 1.65, true, now(), now()),
    ('farm-rooster', 'farm', 'farm', 'Животни', 'Петел', 45, '/reward-assets/farm/rooster.svg', 0.85, 0.40, 1.85, true, now(), now()),
    ('farm-chick', 'farm', 'farm', 'Животни', 'Пиленце', 25, '/reward-assets/farm/chick.svg', 0.60, 0.30, 1.35, true, now(), now()),
    ('farm-duck', 'farm', 'farm', 'Животни', 'Патица', 40, '/reward-assets/farm/duck.svg', 0.82, 0.38, 1.80, true, now(), now()),
    ('farm-duckling', 'farm', 'farm', 'Животни', 'Патенце', 25, '/reward-assets/farm/duckling.svg', 0.60, 0.30, 1.35, true, now(), now()),
    ('farm-goose', 'farm', 'farm', 'Животни', 'Гъска', 45, '/reward-assets/farm/goose.svg', 0.90, 0.40, 1.90, true, now(), now()),
    ('farm-gosling', 'farm', 'farm', 'Животни', 'Гъсенце', 30, '/reward-assets/farm/gosling.svg', 0.62, 0.30, 1.40, true, now(), now()),
    ('farm-cow', 'farm', 'farm', 'Животни', 'Крава', 80, '/reward-assets/farm/cow.svg', 1.10, 0.55, 2.35, true, now(), now()),
    ('farm-bull', 'farm', 'farm', 'Животни', 'Бик', 85, '/reward-assets/farm/bull.svg', 1.15, 0.55, 2.45, true, now(), now()),
    ('farm-calf', 'farm', 'farm', 'Животни', 'Теле', 55, '/reward-assets/farm/calf.svg', 0.85, 0.40, 1.85, true, now(), now()),
    ('farm-horse', 'farm', 'farm', 'Животни', 'Кон', 80, '/reward-assets/farm/horse.svg', 1.10, 0.55, 2.35, true, now(), now()),
    ('farm-mare', 'farm', 'farm', 'Животни', 'Кобила', 80, '/reward-assets/farm/mare.svg', 1.08, 0.55, 2.30, true, now(), now()),
    ('farm-foal', 'farm', 'farm', 'Животни', 'Жребче', 55, '/reward-assets/farm/foal.svg', 0.82, 0.40, 1.80, true, now(), now()),
    ('farm-pig-sow', 'farm', 'farm', 'Животни', 'Прасе майка', 60, '/reward-assets/farm/pig-sow.svg', 1.00, 0.45, 2.10, true, now(), now()),
    ('farm-pig-boar', 'farm', 'farm', 'Животни', 'Глиган', 65, '/reward-assets/farm/pig-boar.svg', 1.05, 0.50, 2.20, true, now(), now()),
    ('farm-piglet', 'farm', 'farm', 'Животни', 'Прасенце', 35, '/reward-assets/farm/piglet.svg', 0.70, 0.35, 1.55, true, now(), now()),
    ('farm-barn', 'farm', 'farm', 'Сгради', 'Хамбар', 120, '/reward-assets/farm/barn.svg', 1.35, 0.65, 2.70, true, now(), now()),
    ('farm-stable', 'farm', 'farm', 'Сгради', 'Конюшня', 110, '/reward-assets/farm/stable.svg', 1.35, 0.65, 2.70, true, now(), now()),
    ('farm-chicken-coop', 'farm', 'farm', 'Сгради', 'Кокошарник', 90, '/reward-assets/farm/chicken-coop.svg', 1.15, 0.55, 2.35, true, now(), now()),
    ('farm-house', 'farm', 'farm', 'Сгради', 'Фермерска къща', 130, '/reward-assets/farm/farm-house.svg', 1.35, 0.65, 2.70, true, now(), now()),
    ('farm-silo', 'farm', 'farm', 'Сгради', 'Силоз', 95, '/reward-assets/farm/silo.svg', 1.15, 0.55, 2.35, true, now(), now()),
    ('farm-well', 'farm', 'farm', 'Предмети', 'Кладенец', 55, '/reward-assets/farm/well.svg', 0.95, 0.45, 2.00, true, now(), now()),
    ('farm-fence', 'farm', 'farm', 'Предмети', 'Ограда', 25, '/reward-assets/farm/fence.svg', 1.15, 0.55, 2.50, true, now(), now()),
    ('farm-gate', 'farm', 'farm', 'Предмети', 'Порта', 35, '/reward-assets/farm/gate.svg', 1.05, 0.50, 2.30, true, now(), now()),
    ('farm-farmer', 'farm', 'farm', 'Хора', 'Фермер', 70, '/reward-assets/farm/farmer.svg', 0.95, 0.45, 1.95, true, now(), now()),
    ('farm-farmer-woman', 'farm', 'farm', 'Хора', 'Фермерка', 70, '/reward-assets/farm/farmer-woman.svg', 0.95, 0.45, 1.95, true, now(), now()),
    ('farm-child-farmer', 'farm', 'farm', 'Хора', 'Малък помощник', 55, '/reward-assets/farm/child-farmer.svg', 0.82, 0.40, 1.75, true, now(), now()),
    ('farm-tractor', 'farm', 'farm', 'Машини', 'Трактор', 130, '/reward-assets/farm/tractor.svg', 1.25, 0.60, 2.65, true, now(), now()),
    ('farm-hay-bale', 'farm', 'farm', 'Предмети', 'Бала сено', 25, '/reward-assets/farm/hay-bale.svg', 0.95, 0.45, 2.00, true, now(), now()),
    ('farm-hay-stack', 'farm', 'farm', 'Предмети', 'Купа сено', 35, '/reward-assets/farm/hay-stack.svg', 1.05, 0.50, 2.25, true, now(), now()),
    ('farm-cart', 'farm', 'farm', 'Предмети', 'Дървена количка', 45, '/reward-assets/farm/cart.svg', 1.00, 0.50, 2.15, true, now(), now()),
    ('farm-watering-can', 'farm', 'farm', 'Предмети', 'Лейка', 25, '/reward-assets/farm/watering-can.svg', 0.80, 0.38, 1.75, true, now(), now()),
    ('farm-feed-bucket', 'farm', 'farm', 'Предмети', 'Кофа с храна', 25, '/reward-assets/farm/feed-bucket.svg', 0.82, 0.38, 1.75, true, now(), now()),
    ('farm-apple-tree', 'farm', 'farm', 'Природа', 'Ябълково дърво', 55, '/reward-assets/farm/apple-tree.svg', 1.10, 0.55, 2.35, true, now(), now()),
    ('farm-corn', 'farm', 'farm', 'Растения', 'Царевица', 20, '/reward-assets/farm/corn.svg', 0.85, 0.40, 1.85, true, now(), now()),
    ('farm-vegetable-bed', 'farm', 'farm', 'Растения', 'Зеленчукова леха', 35, '/reward-assets/farm/vegetable-bed.svg', 1.10, 0.55, 2.35, true, now(), now()),
    ('farm-sunflower', 'farm', 'farm', 'Растения', 'Слънчоглед', 18, '/reward-assets/farm/sunflower.svg', 0.85, 0.40, 1.80, true, now(), now())
on conflict (id) do update
set theme_id = excluded.theme_id,
    theme_ids = excluded.theme_ids,
    category = excluded.category,
    name = excluded.name,
    price = excluded.price,
    image = excluded.image,
    default_scale = excluded.default_scale,
    min_scale = excluded.min_scale,
    max_scale = excluded.max_scale,
    active = true,
    updated_at = now();
